# .streamlit/secrets.toml

GEMINI_API_KEY = "AIzaSyB3WFTEabrpSpe0Vx0yBlHVh2jrXiFH6Sg"

# Supabase Postgres Credentials
DB_HOST = "aws-1-ap-southeast-1.pooler.supabase.com"
DB_PORT = "5432"
DB_USER = "postgres.pwceitepzzucevvztohh"
DB_PASS = "capitup_dash"
DB_NAME = "postgres"